var link=videojs.extend(videojs.getComponent('Component'));link.prototype.createEl=function createEl(){var a=$("<a/>");a.attr('href',this.options_.href);a.attr('id',this.options_.id);if(this.options_.download){a.attr('download',true);}
a.attr('id',this.options_.id);a.attr('target',"_blank");a.html(this.options_.text);return $(a).get(0);};videojs.registerComponent('Link',link);var dom=videojs.extend(videojs.getComponent('Component'));dom.prototype.createEl=function createEl(){return $(this.options_.html).get(0);};videojs.registerComponent('Dom',dom);$('body').delegate('.vjs-progress-control','click',function(e){var target=$(e.target);if(target.is('.vjs-progress-control.vjs-control')){var seek_to=target.find('.vjs-mouse-display').attr('data-current-time');player.currentTime(humanTimeToSeconds(seek_to));}});function humanTimeToSeconds(str){var hour=0;var minute=0;var seconds=0;var matches;if(matches=str.match(/^(\d+):(\d+)$/)){minute=parseInt(matches[1]);seconds=parseInt(matches[2]);}else if(matches=str.match(/^(\d+):(\d+):(\d+)$/)){hour=parseInt(matches[1]);minute=parseInt(matches[2]);seconds=parseInt(matches[3]);}
return hour*3600+minute*60+seconds;}
var player_loading_process=0;var interval_handler;function addPlayerLoadingProcess(incr){player_loading_process+=incr;if(player_loading_process>=100){player_loading_process=100;clearInterval(interval_handler);}
$('#loading .player-process').animate({'width':player_loading_process+'%'},100);}
interval_handler=setInterval(function(){addPlayerLoadingProcess(3);},1000);$('#share_layer .btn').click(function(){if($(this).text()=='Link'){$('#share_layer .label').text('Link:');$('#share_layer input').val($(this).attr('data-link'));$(this).text('Embed');}else{$('#share_layer .label').text('Embed:');$('#share_layer input').val($(this).attr('data-embed'));$(this).text('Link');}});$('#share_layer').click(function(event){if($(event.target).is('.addthis_toolbox')||$(event.target).parents('.addthis_toolbox').length||$(event.target).is('.copy')||$(event.target).parents('.copy').length){}else{$(this).hide();}});function init(player,logUrl){var first=0;player.on("play",function(e){if(first==0){if(logUrl){$.ajax({url:logUrl,type:'GET',xhrFields:{withCredentials:true},crossDomain:true,});}
first++;}});playerApi(player);}
function playerApi(player){window.addEventListener('message',function(event){if(typeof(event.data)==='object'&&event.data.action&&event.data.action.search('PB.Widget.API.')!==-1){try{var action=event.data.action.replace('PB.Widget.API.','');switch(action){case 'PLAY':player.play();break;case 'PAUSE':player.pause();break;case 'NEXT':if(player.playlist){player.playlist.next();}
break;case 'PREV':if(player.playlist){player.playlist.previous();}
break;case 'TOGGLE':if(player.paused()){player.play();}else{player.pause();}
break;case 'SEEK_TO':player.currentTime(event.data.value);break;case 'SET_VOLUME':player.volume(event.data.value/100.0);break;case 'SKIP':if(player.playlist){player.playlist.currentItem(parseInt(event.data.value));}
break;case 'GET_VOLUME':postGetterCallback(action,player.volume()*100);break;case 'GET_DURATION':postGetterCallback(action,player.duration());break;case 'GET_POSITION':postGetterCallback(action,player.currentTime());break;case 'GET_PAUSED':postGetterCallback(action,player.paused());break;case 'GET_SOURCES':if(player.playlist){postGetterCallback(action,player.playlist());}else{postGetterCallback(action,[player.source]);}
break;case 'GET_CURRENTSOURCE':if(player.playlist){postGetterCallback(action,player.playlist()[player.playlist.currentItem()]);}else{postGetterCallback(action,player.source);}
break;case 'GET_CURRENTSOURCEINDEX':if(player.playlist){postGetterCallback(action,player.playlist.currentItem());}else{postGetterCallback(action,0);}
break;}}catch(e){}}});function getPlayerData(){var buffered=player.buffered();var duration=player.duration();var data={};data.currentPosition=player.currentTime();if(duration>0){data.loadedProgress=buffered.end(buffered.length-1)/duration;data.relativePosition=data.currentPosition/duration;}else{data.relativePosition=0;data.loadedProgress=0;}
return data;}
function postEvent(eventName){window.parent.postMessage({event:eventName,data:getPlayerData()},'*');}
function postGetterCallback(action,value){window.parent.postMessage({event:'PB.Widget.API.CALLBACK.'+action,data:value},'*');}
var start_at=0,end_at=0;player.on('timeupdate',function(event){if(end_at==0){end_at=player.currentTime();}
if(Math.abs(player.currentTime()-end_at)>1){pushStats();start_at=player.currentTime();}
end_at=player.currentTime();postEvent("PB.Widget.Events.PLAY_PROGRESS");});player.on('progress',function(event){postEvent("PB.Widget.Events.LOAD_PROGRESS");});player.on('playing',function(event){postEvent("PB.Widget.Events.PLAY");});player.on('pause',function(event){postEvent("PB.Widget.Events.PAUSE");});player.on('ended',function(event){pushStats();postEvent("PB.Widget.Events.FINISH");});player.on('seeked',function(event){postEvent("PB.Widget.Events.SEEK");});player.on('ready',function(event){postEvent("PB.Widget.Events.READY");});$('body').delegate('.vjs-button.vjs-playing','click',function(e){pushStats();});function pushStats(){var _start_at=Math.floor(start_at);end_at=Math.floor(end_at);start_at=end_at;if(end_at-_start_at<3){return;}
console.log('stats',_start_at,end_at);if(typeof(sui)!='undefined'){var url="https://d1.podbean.com/webplayer_engagement?"+$.param({u:sui,s:_start_at,e:end_at,v:guid()});if(typeof(navigator.sendBeacon)!=='undefined'){navigator.sendBeacon(url+'&beacon=1');}else{$.post(url+'&post=1');}}}
window.addEventListener("beforeunload",function(e){pushStats();return;});}
function guid(){function s4(){return Math.floor((1+Math.random())*0x10000).toString(16).substring(1);}
return s4()+s4()+'-'+s4()+'-'+s4()+'-'+s4()+'-'+s4()+s4()+s4();}